# Generated by Django 5.2.7 on 2025-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('steam_url', models.URLField()),
                ('discord_url', models.URLField()),
                ('telegram_url', models.URLField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
